### PR TITLE
feat(user): user service + repository

### PR DESCRIPTION
**Pull request by VictorAssunc**
CRUD and initial user service + repository structure.

- I had to make changes to the database lib because it was failing as before.
- When I synchronized a dependency on `go.mod` it changed, I'm not sure if it's right.

To test, I connected to a local database and moved the repository up, so I could call from `server.go`.

Ref #24

### CODE REVIEW

**Comment by VictorAssunc** [comment]
I had a problem on github build:
```
pkg/graphql/internal/resolver/mutation.go:3:6: `mutation` is unused (deadcode)
```

do i need to comment on this or are you going to bypass it?

**Comment by rafaelrubbioli** [comment]
> I had a problem on github build:
> 
> ```
> pkg/graphql/internal/resolver/mutation.go:3:6: `mutation` is unused (deadcode)
> ```
> 
> do i need to comment on this or are you going to bypass it?

you can comment this section

**Comment by VictorAssunc** [comment]
> > I had a problem on github build:
> > ```
> > pkg/graphql/internal/resolver/mutation.go:3:6: `mutation` is unused (deadcode)
> > ```
> > 
> > 
> > do i need to comment on this or are you going to bypass it?
> 
> you can comment this section

ok :+1:

**Review by rafaelrubbioli — APPROVED** [review]
thanks for your contribution! :rocket:

**Pull request merged**
